# Generated by Django 3.1.5 on 2021-01-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210107_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default='', max_length=400),
        ),
    ]
