# Generated by Django 3.1.5 on 2021-01-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210107_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
